{
 "title": "Chikn Farmers Almanac",
 "description": "Track your farm's assets over time!",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Total Farm AVAX Value",
   "type": "stat",
   "description": "Total value of farm in AVAX",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "computed_columns": [
      { "selector": "", "text": "", "type": "string" }
     ],
     "parser": "simple",
     "source": "url",
     "type": "json",
     "url": "https://api.chikn.farm/api/wallet/0x0000000000000000000000000000000000000000/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Total Floor Prices",
   "type": "bargauge",
   "description": "Floor Value of ALL assets",
   "gridPos": { "h": 10, "w": 9, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "source": "url",
     "type": "json",
     "url": "https://api.chikn.farm/api/wallet/0x0000000000000000000000000000000000000000/summary",
     "url_options": {
      "data": "",
      "method": "GET",
      "params": [
       {
        "key": "WALLET",
        "value": "0x0000000000000000000000000000000000000000"
       }
      ]
     }
    }
   ]
  },
  {
   "title": "Total Chikn",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "source": "url",
     "type": "json",
     "url": "https://api.chikn.farm/api/wallet/0x0000000000000000000000000000000000000000/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "My Items Total Floor Value",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "chikn_farm_chiknCraftedItemFloorValue",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "My Items",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "expr": "chikn_farm_totalChiknCraftedItem",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Roostr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "source": "url",
     "type": "json",
     "url": "https://api.chikn.farm/api/wallet/0x0000000000000000000000000000000000000000/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Total Egg Received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\r\n| project \"Egg Received\"=\"eggReport.received\"",
     "url": "https://api.chikn.farm/api/wallet/0x0000000000000000000000000000000000000000/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "My FL Total Floor Value",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 4 },
   "targets": [
    { "expr": "chikn_farm_farmlandFloorValue", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Farmland",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "source": "url",
     "type": "json",
     "url": "https://api.chikn.farm/api/wallet/0x0000000000000000000000000000000000000000/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Total Egg Sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\r\n| project \"Egg Sent\"=\"eggReport.sent\"",
     "url": "https://api.chikn.farm/api/wallet/0x0000000000000000000000000000000000000000/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Total Items",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "source": "url",
     "type": "json",
     "url": "https://api.chikn.farm/api/wallet/0x0000000000000000000000000000000000000000/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "My EGG Burned",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 9 },
   "targets": [
    { "expr": "chikn_farm_eggReport_burned", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Egg Burned",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\r\n| project \"Egg Burned\"=\"eggReport.burned\"",
     "url": "https://api.chikn.farm/api/wallet/0x0000000000000000000000000000000000000000/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Current Egg Balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\r\n| project \"Egg Balance\"=\"eggReport.balance\"",
     "url": "https://api.chikn.farm/api/wallet/0x0000000000000000000000000000000000000000/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Total Egg Minted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\r\n| project \"Egg Minted\"=\"eggReport.minted\"",
     "url": "https://api.chikn.farm/api/wallet/0x0000000000000000000000000000000000000000/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "My BP Total Floor Value",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 13 },
   "targets": [
    { "expr": "chikn_farm_blueprintFloorValue", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "My Chikn Total Floor Value",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 13 },
   "targets": [
    { "expr": "chikn_farm_floorValue", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "My Roostr Total Floor Value",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 13 },
   "targets": [
    { "expr": "chikn_farm_roostrFloorValue", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "My EGG Minted",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 14 },
   "targets": [
    { "expr": "chikn_farm_eggReport_minted", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Daily Egg Burn",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "source": "url",
     "type": "json",
     "url": "https://api.chikn.farm/api/reports/EggDailyBurn",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}