global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 15s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "chikn_farm_wallet_summary"
    scrape_interval: 3m
    static_configs:
      - targets: ["localhost:8000"]
